In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import spatial
from sklearn.metrics.pairwise import pairwise_distances
from textblob import TextBlob
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import PCA
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split

In [2]:
%ls

DSC148_Midterm_W24_v1.pdf          homework01.ipynb
Digital_Music_5.json               homework02 - Jupyter Notebook.pdf
Movies_and_TV_5.json               homework02.ipynb
Untitled.ipynb                     homework02.pdf
car_evaluation.csv                 homework03.ipynb
dm_challenge/                      homework03.pdf
dsc148_hw01.pdf                    iris.csv
dsc148_hw03_q2.pdf                 menu.csv
dsc148_midterm.pdf                 midterm.ipynb
final_project.ipynb                wine.csv
homework01 - Jupyter Notebook.pdf

In [3]:
df = pd.read_json('Digital_Music_5.json', lines=True)

In [4]:
df.shape

(169781, 12)

In [5]:
df.head()

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,image
0,5,3.0,True,"06 3, 2013",A2TYZ821XXK2YZ,3426958910,{'Format:': ' Audio CD'},Garrett,"This is awesome to listen to, A must-have for ...",Slayer Rules!,1370217600,NaN
1,5,NaN,True,"10 11, 2014",A3OFSREZADFUDY,3426958910,{'Format:': ' Audio CD'},Ad,bien,Five Stars,1412985600,NaN
2,5,NaN,True,"02 11, 2014",A2VAMODP8M77NG,3426958910,{'Format:': ' Audio CD'},JTGabq,It was great to hear the old stuff again and I...,SLAYER!!!!!!!!!!!!!!!!!!!!!,1392076800,NaN
3,4,3.0,False,"12 7, 2013",AAKSLZ9IDTEH0,3426958910,{'Format:': ' Audio CD'},john F&#039;n doe,well best of's are a bit poison normally but t...,slayer greatest hits! you mean everything righ...,1386374400,NaN
4,5,NaN,True,"06 12, 2016",A3OH43OZJLKI09,5557706259,{'Format:': ' Audio CD'},melinda a goodman,What can I say? This is Casting Crowns!!!This ...,"This is a good, blessing filled",1465689600,NaN

In [6]:
df['style'] = df['style'].astype(str)
df['style'] = df['style'].apply(lambda x: x.split(':')[-1].strip(" }'"))

## Train test split

In [7]:
df

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,image
0,5,3.0,True,"06 3, 2013",A2TYZ821XXK2YZ,3426958910,Audio CD,Garrett,"This is awesome to listen to, A must-have for ...",Slayer Rules!,1370217600,NaN
1,5,NaN,True,"10 11, 2014",A3OFSREZADFUDY,3426958910,Audio CD,Ad,bien,Five Stars,1412985600,NaN
2,5,NaN,True,"02 11, 2014",A2VAMODP8M77NG,3426958910,Audio CD,JTGabq,It was great to hear the old stuff again and I...,SLAYER!!!!!!!!!!!!!!!!!!!!!,1392076800,NaN
3,4,3.0,False,"12 7, 2013",AAKSLZ9IDTEH0,3426958910,Audio CD,john F&#039;n doe,well best of's are a bit poison normally but t...,slayer greatest hits! you mean everything righ...,1386374400,NaN
4,5,NaN,True,"06 12, 2016",A3OH43OZJLKI09,5557706259,Audio CD,melinda a goodman,What can I say? This is Casting Crowns!!!This ...,"This is a good, blessing filled",1465689600,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
169776,5,NaN,True,"08 19, 2018",A1SR2T84IXOMAQ,B01HJ91MTW,MP3 Music,Diane B.,Casting Crowns songs are all wonderful!!,Great song!!,1534636800,NaN
169777,5,NaN,True,"03 18, 2018",A2SR3DWJR1PYR6,B01HJ91MTW,MP3 Music,jan c.,Just reminds you that you are never alone.,Five Stars,1521331200,NaN
169778,5,NaN,True,"03 7, 2018",A24V7X30NIMOIY,B01HJ91MTW,MP3 Music,Lori Y,"Good product, good service.",Five Stars,1520380800,NaN
169779,5,NaN,True,"02 12, 2018",A1LW10GYP2EYM1,B01HJ91MTW,MP3 Music,N F,I love every single song this group sings. The...,Absolutely beautiful...,1518393600,NaN
169780,5,NaN,True,"01 27, 2018",A26TH3YW0QWPI7,B01HJ91MTW,MP3 Music,Susan Lane,Great song,Five Stars,1517011200,NaN

In [8]:
X = df
y = df['overall']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [9]:
X_train

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,image
169730,5,NaN,False,"04 13, 2017",AGMN8LD18M7LG,B01H5ZYVDY,MP3 Music,jackie80,"this is an awesome song, I don't know I passed...",dont pass it up,1492041600,NaN
43611,5,NaN,True,"06 26, 2014",A1F3YG4KFRNN1F,B00136NOVM,MP3 Music,Jo Ann,First of all I like Alan Jackson and most of h...,Remember When by Alan Jackson,1403740800,NaN
96370,5,NaN,True,"01 9, 2015",A1TKP7591K5CXX,B00HO15UFI,MP3 Music,jl,I only know of his music from the fast and fur...,Don,1420761600,NaN
68403,5,NaN,True,"08 18, 2014",A2XE7SG4ZFAOIB,B004GKI7AU,Audio CD,Lucinda,good choice of songs to add to your collection.,great for your collection.,1408320000,NaN
1608,5,NaN,True,"05 29, 2014",A2MRABB6S0JGL8,B000SZZFUC,MP3 Music,Phil,great music. fast download. Recommend this art...,Great a Music,1401321600,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
119879,5,NaN,True,"09 6, 2016",A1S3HHMAB9LLXK,B01G9RNZXG,Audio CD,Matthew D&#039;Souza,"Incredibly fun, smooth, and wacky instrumental...",The Avalanches Come Back Roaring and Grooving!,1473120000,NaN
103694,5,NaN,True,"04 29, 2015",A1P3H3DODU5EBP,B00NJMNLRK,MP3 Music,jabrd76,"Very thought provoking lyrics, but a real blue...",Another good one from LBT,1430265600,NaN
131932,5,NaN,True,"05 4, 2018",AA77F985K4AEL,B0012422HM,nan,Gregg H.,Reminds me of my younger days!,Love the Song,1525392000,NaN
146867,5,NaN,True,"07 19, 2015",A1RPR38LB5B924,B001OGPTTQ,MP3 Music,Estelle59,An all time favorite. It brings back lots of ...,Holding on to Yesterday,1437264000,NaN
121958,5,NaN,True,"09 18, 2015",A748G1WWJBENH,B000TDWQEQ,MP3 Music,Dana Jackson,Excellent quality music! Very happy!,Five Stars,1442534400,NaN

In [10]:
X_train['reviewerID'].nunique()

16566

## User / Product Similarity

In [11]:
product = X_train[['overall', 'reviewerID', 'asin', 'style', 'reviewText']].reset_index()
product.head()

,index,overall,reviewerID,asin,style,reviewText
0,169730,5,AGMN8LD18M7LG,B01H5ZYVDY,MP3 Music,"this is an awesome song, I don't know I passed..."
1,43611,5,A1F3YG4KFRNN1F,B00136NOVM,MP3 Music,First of all I like Alan Jackson and most of h...
2,96370,5,A1TKP7591K5CXX,B00HO15UFI,MP3 Music,I only know of his music from the fast and fur...
3,68403,5,A2XE7SG4ZFAOIB,B004GKI7AU,Audio CD,good choice of songs to add to your collection.
4,1608,5,A2MRABB6S0JGL8,B000SZZFUC,MP3 Music,great music. fast download. Recommend this art...

In [12]:
product['reviewText'].isnull().sum()

134

In [13]:
product['reviewText'].fillna('', inplace=True)

In [14]:
product.head()

,index,overall,reviewerID,asin,style,reviewText
0,169730,5,AGMN8LD18M7LG,B01H5ZYVDY,MP3 Music,"this is an awesome song, I don't know I passed..."
1,43611,5,A1F3YG4KFRNN1F,B00136NOVM,MP3 Music,First of all I like Alan Jackson and most of h...
2,96370,5,A1TKP7591K5CXX,B00HO15UFI,MP3 Music,I only know of his music from the fast and fur...
3,68403,5,A2XE7SG4ZFAOIB,B004GKI7AU,Audio CD,good choice of songs to add to your collection.
4,1608,5,A2MRABB6S0JGL8,B000SZZFUC,MP3 Music,great music. fast download. Recommend this art...

In [15]:
stop_words = set(stopwords.words('english'))

In [16]:
def remove_stopwords(text):
    word_tokens = word_tokenize(text)
    filtered_text = [word for word in word_tokens if word.lower() not in stop_words and word not in string.punctuation]
    return ' '.join(filtered_text)

In [17]:
product['reviewText'] = product['reviewText'].apply(remove_stopwords)

In [18]:
product.head()

,index,overall,reviewerID,asin,style,reviewText
0,169730,5,AGMN8LD18M7LG,B01H5ZYVDY,MP3 Music,awesome song n't know passed downloading new m...
1,43611,5,A1F3YG4KFRNN1F,B00136NOVM,MP3 Music,First like Alan Jackson recordings like one re...
2,96370,5,A1TKP7591K5CXX,B00HO15UFI,MP3 Music,know music fast furious move 's started listen...
3,68403,5,A2XE7SG4ZFAOIB,B004GKI7AU,Audio CD,good choice songs add collection
4,1608,5,A2MRABB6S0JGL8,B000SZZFUC,MP3 Music,great music fast download Recommend artists.dr...

In [19]:
vectorizer = CountVectorizer()

In [20]:
bag_of_words = vectorizer.fit_transform(product['reviewText'])

In [71]:
n_components = 20
svd = TruncatedSVD(n_components=n_components)
reduced_bow = svd.fit_transform(bag_of_words)

In [72]:
reduced_bow

array([[ 0.13956617, -1.03335203, -0.09600151, ..., -0.17426193,
        -0.01929291,  0.0725842 ],
       [ 0.11777706, -0.87307662, -0.13642838, ..., -0.73943945,
         0.05250194, -0.87453003],
       [ 0.08169365, -0.53069485, -0.06949431, ..., -0.41446679,
        -0.01011001, -0.27233773],
       ...,
       [ 0.0037747 , -0.02733568, -0.0042738 , ...,  0.00978031,
        -0.00597081,  0.00971295],
       [ 0.02693246, -0.21963541, -0.03465028, ...,  0.04943949,
        -0.01311788,  0.05421879],
       [ 0.05148526, -0.25145644, -0.01896118, ..., -0.00712258,
        -0.01417873, -0.06363764]])

In [73]:
reduced_bow_df = pd.DataFrame(reduced_bow, columns=[f'component_{i+1}' for i in range(n_components)])

In [74]:
reduced_bow_df.head()

,component_1,component_2,component_3,component_4,component_5,component_6,component_7,component_8,component_9,component_10,component_11,component_12,component_13,component_14,component_15,component_16,component_17,component_18,component_19,component_20
0,0.139566,-1.033352,-0.096002,-0.673636,0.068532,0.076260,0.187784,0.508483,-0.757082,-0.215701,0.479036,0.034859,-0.204837,-0.483611,0.093922,-0.067586,0.102889,-0.174262,-0.019293,0.072584
1,0.117777,-0.873077,-0.136428,0.337059,0.007509,-0.005542,-0.314951,0.025478,0.023709,0.041685,-0.460351,0.162574,-0.606657,0.944318,-0.081463,0.735716,0.180767,-0.739439,0.052502,-0.874530
2,0.081694,-0.530695,-0.069494,0.197873,-0.004794,0.082559,-0.189611,0.331766,-0.545953,-0.147211,-0.456994,0.060986,-0.497165,-0.216158,0.120253,0.624344,0.018322,-0.414467,-0.010110,-0.272338
3,0.045775,-0.352612,-0.043033,0.096993,-0.002586,-0.010292,-0.106954,0.059010,-0.086109,-0.040854,-0.120049,0.003601,-0.181788,0.259823,-0.081061,-0.107098,-1.030450,0.705035,0.026618,0.031994
4,0.227065,-1.360770,-0.142809,0.323243,-0.023771,0.329108,-0.283524,1.631408,-2.723521,-0.788605,-0.455840,0.040583,-1.008311,-1.719906,0.439118,0.461355,-0.151140,-0.685296,-0.073438,-0.573125

In [75]:
43611 in reduced_bow_df.index

True

In [76]:
reduced_bow_df.shape

(152802, 20)

In [77]:
product.shape

(152802, 6)

In [78]:
copy = pd.concat([product, reduced_bow_df], axis=1)

In [79]:
copy.head()

,index,overall,reviewerID,asin,style,reviewText,component_1,component_2,component_3,component_4,...,component_11,component_12,component_13,component_14,component_15,component_16,component_17,component_18,component_19,component_20
0,169730,5,AGMN8LD18M7LG,B01H5ZYVDY,MP3 Music,awesome song n't know passed downloading new m...,0.139566,-1.033352,-0.096002,-0.673636,...,0.479036,0.034859,-0.204837,-0.483611,0.093922,-0.067586,0.102889,-0.174262,-0.019293,0.072584
1,43611,5,A1F3YG4KFRNN1F,B00136NOVM,MP3 Music,First like Alan Jackson recordings like one re...,0.117777,-0.873077,-0.136428,0.337059,...,-0.460351,0.162574,-0.606657,0.944318,-0.081463,0.735716,0.180767,-0.739439,0.052502,-0.874530
2,96370,5,A1TKP7591K5CXX,B00HO15UFI,MP3 Music,know music fast furious move 's started listen...,0.081694,-0.530695,-0.069494,0.197873,...,-0.456994,0.060986,-0.497165,-0.216158,0.120253,0.624344,0.018322,-0.414467,-0.010110,-0.272338
3,68403,5,A2XE7SG4ZFAOIB,B004GKI7AU,Audio CD,good choice songs add collection,0.045775,-0.352612,-0.043033,0.096993,...,-0.120049,0.003601,-0.181788,0.259823,-0.081061,-0.107098,-1.030450,0.705035,0.026618,0.031994
4,1608,5,A2MRABB6S0JGL8,B000SZZFUC,MP3 Music,great music fast download Recommend artists.dr...,0.227065,-1.360770,-0.142809,0.323243,...,-0.455840,0.040583,-1.008311,-1.719906,0.439118,0.461355,-0.151140,-0.685296,-0.073438,-0.573125

In [80]:
one_hot_encoded = pd.get_dummies(product['style'])

In [81]:
product['style'].nunique()

11

In [82]:
one_hot_encoded = one_hot_encoded.iloc[:, :-1]

In [83]:
one_hot_encoded

,Amazon Video,Audio CD,Audio Cassette,Blu-ray,Blu-ray Audio,DVD,DVD Audio,MP3 Music,Vinyl,Vinyl Bound
0,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,0,1,0,0
3,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
152797,0,1,0,0,0,0,0,0,0,0
152798,0,0,0,0,0,0,0,1,0,0
152799,0,0,0,0,0,0,0,0,0,0
152800,0,0,0,0,0,0,0,1,0,0
152801,0,0,0,0,0,0,0,1,0,0

In [84]:
copy = pd.concat([copy, one_hot_encoded], axis=1)
copy.head()

,index,overall,reviewerID,asin,style,reviewText,component_1,component_2,component_3,component_4,...,Amazon Video,Audio CD,Audio Cassette,Blu-ray,Blu-ray Audio,DVD,DVD Audio,MP3 Music,Vinyl,Vinyl Bound
0,169730,5,AGMN8LD18M7LG,B01H5ZYVDY,MP3 Music,awesome song n't know passed downloading new m...,0.139566,-1.033352,-0.096002,-0.673636,...,0,0,0,0,0,0,0,1,0,0
1,43611,5,A1F3YG4KFRNN1F,B00136NOVM,MP3 Music,First like Alan Jackson recordings like one re...,0.117777,-0.873077,-0.136428,0.337059,...,0,0,0,0,0,0,0,1,0,0
2,96370,5,A1TKP7591K5CXX,B00HO15UFI,MP3 Music,know music fast furious move 's started listen...,0.081694,-0.530695,-0.069494,0.197873,...,0,0,0,0,0,0,0,1,0,0
3,68403,5,A2XE7SG4ZFAOIB,B004GKI7AU,Audio CD,good choice songs add collection,0.045775,-0.352612,-0.043033,0.096993,...,0,1,0,0,0,0,0,0,0,0
4,1608,5,A2MRABB6S0JGL8,B000SZZFUC,MP3 Music,great music fast download Recommend artists.dr...,0.227065,-1.360770,-0.142809,0.323243,...,0,0,0,0,0,0,0,1,0,0

In [85]:
features = copy.iloc[:, 6:]
features.head()

,component_1,component_2,component_3,component_4,component_5,component_6,component_7,component_8,component_9,component_10,...,Amazon Video,Audio CD,Audio Cassette,Blu-ray,Blu-ray Audio,DVD,DVD Audio,MP3 Music,Vinyl,Vinyl Bound
0,0.139566,-1.033352,-0.096002,-0.673636,0.068532,0.076260,0.187784,0.508483,-0.757082,-0.215701,...,0,0,0,0,0,0,0,1,0,0
1,0.117777,-0.873077,-0.136428,0.337059,0.007509,-0.005542,-0.314951,0.025478,0.023709,0.041685,...,0,0,0,0,0,0,0,1,0,0
2,0.081694,-0.530695,-0.069494,0.197873,-0.004794,0.082559,-0.189611,0.331766,-0.545953,-0.147211,...,0,0,0,0,0,0,0,1,0,0
3,0.045775,-0.352612,-0.043033,0.096993,-0.002586,-0.010292,-0.106954,0.059010,-0.086109,-0.040854,...,0,1,0,0,0,0,0,0,0,0
4,0.227065,-1.360770,-0.142809,0.323243,-0.023771,0.329108,-0.283524,1.631408,-2.723521,-0.788605,...,0,0,0,0,0,0,0,1,0,0

In [86]:
pv = pd.pivot_table(X_train, values='overall', index=['reviewerID'], columns=['asin'])
pv.head()

asin,3426958910,5557505946,5557706259,5559166928,7799420340,9434682614,9714721180,9721717150,B000002TTH,B000006045,...,B01HF1Z8JO,B01HFCKRA8,B01HGB5USC,B01HGB68GK,B01HGOZSHM,B01HHQSCDQ,B01HIY8QVU,B01HJ91HEC,B01HJ91LIY,B01HJ91MTW
reviewerID,,,,,,,,,,,,,,,,,,,,,
A0072041HVZ3465DXUOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A0081575F2F9XQSSIYA3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A0638585LHS5R1XDIOGY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A1006TXWG76H0N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A100UXMXYOQU1X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
pv.reset_index()

asin,reviewerID,3426958910,5557505946,5557706259,5559166928,7799420340,9434682614,9714721180,9721717150,B000002TTH,...,B01HF1Z8JO,B01HFCKRA8,B01HGB5USC,B01HGB68GK,B01HGOZSHM,B01HHQSCDQ,B01HIY8QVU,B01HJ91HEC,B01HJ91LIY,B01HJ91MTW
0,A0072041HVZ3465DXUOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A0081575F2F9XQSSIYA3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A0638585LHS5R1XDIOGY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A1006TXWG76H0N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A100UXMXYOQU1X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16561,AZXWUZ9PPSOTL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16562,AZY0M1ANDSEPL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16563,AZYOVGJLQ03ML,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16564,AZYPOLLSDVG4K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16565,AZZHILYMITLGM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
user_user = pv.reset_index().set_index('reviewerID')
user_user.head()

asin,3426958910,5557505946,5557706259,5559166928,7799420340,9434682614,9714721180,9721717150,B000002TTH,B000006045,...,B01HF1Z8JO,B01HFCKRA8,B01HGB5USC,B01HGB68GK,B01HGOZSHM,B01HHQSCDQ,B01HIY8QVU,B01HJ91HEC,B01HJ91LIY,B01HJ91MTW
reviewerID,,,,,,,,,,,,,,,,,,,,,
A0072041HVZ3465DXUOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A0081575F2F9XQSSIYA3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A0638585LHS5R1XDIOGY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A1006TXWG76H0N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A100UXMXYOQU1X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
user_user['3426958910'].sum()

24.0

In [89]:
user_user.fillna(0, inplace=True)

In [90]:
pv.columns

Index(['3426958910', '5557505946', '5557706259', '5559166928', '7799420340',
       '9434682614', '9714721180', '9721717150', 'B000002TTH', 'B000006045',
       ...
       'B01HF1Z8JO', 'B01HFCKRA8', 'B01HGB5USC', 'B01HGB68GK', 'B01HGOZSHM',
       'B01HHQSCDQ', 'B01HIY8QVU', 'B01HJ91HEC', 'B01HJ91LIY', 'B01HJ91MTW'],
      dtype='object', name='asin', length=11792)

In [91]:
num_users = len(pv)
similarity_matrix = np.zeros((num_users, num_users))

In [92]:
num_users

16566

In [93]:
similarity_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [94]:
user_user_np = user_user.to_numpy()

In [95]:
user_user_np[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [96]:
def cosine_similarity(u, v):
    return np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

for i in range(num_users):
    for j in range(i, num_users):
#         print(cosine_similarity(user_user.iloc[i].values.reshape(-1, 1), user_user.iloc[j].values.reshape(-1, 1)))
        similarity_matrix[i, j] = cosine_similarity(user_user_np[i], user_user_np[j])

KeyboardInterrupt:

In [101]:
similarity_matrix[50][50]

0.9999999999999998

## RUN TILL ABOVE

In [142]:
def cos_sim(row_index, top_n = 10):
    row = features.iloc[row_index].values
    similarities = []
    for i in range(len(features)):
        if i != row_index:
            similarities.append((cosine_similarity(row.reshape(1, -1), features.iloc[i].values.reshape(1, -1))[0][0], i))
    similarities = sorted(similarities)[-top_n:]
    return similarities

In [143]:
features.fillna(0, inplace=True)

In [144]:
# features.iloc[129338]

In [146]:
test = cos_sim(129338)

In [150]:
for i in test:
    print(product.iloc[i[-1]]['summary'], product.iloc[i[-1]]['style'])

80 's Time MP3 Music
good MP3 Music
Nice music MP3 Music
Enjoy listening Bose headphones MP3 Music
classic kid MP3 Music
Liked MP3 Music
Five Stars MP3 Music
Five Stars MP3 Music
Five Stars MP3 Music
Another good one LBT MP3 Music

In [61]:
row = features.iloc[0]
row

component_1    1.520545e-08
component_2    2.744296e-05
component_3   -5.183007e-05
component_4    6.331035e-07
component_5    6.405343e-05
                   ...
DVD            0.000000e+00
DVD Audio      0.000000e+00
MP3 Music      0.000000e+00
Vinyl          0.000000e+00
Vinyl Bound    0.000000e+00
Name: 0, Length: 210, dtype: float64

In [63]:
cosine_similarity(row.values.reshape(1, -1), features.iloc[1].values.reshape(1, -1))[0][0]

0.577226453706312

In [5]:
df['asin'].nunique()

11797

In [6]:
unique_products = df['asin'].unique()
asin_dict = {}
for idx, prod in enumerate(unique_products):
    asin_dict[prod] = idx
asin_dict['3426958910']

0

In [7]:
unique_users = df['reviewerID'].unique()
user_dict = {}
for idx, prod in enumerate(unique_users):
    user_dict[prod] = idx
user_dict['A2TYZ821XXK2YZ']

0

In [8]:
df['reviewer_idx'] = [user_dict[i] for i in df['reviewerID']]

In [9]:
# asin_dict.keys()

In [10]:
df['unique_prod_idx'] = [asin_dict[i] for i in df['asin']]

In [11]:
df.head()

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,image,reviewer_idx,unique_prod_idx
0,5,3.0,True,"06 3, 2013",A2TYZ821XXK2YZ,3426958910,{'Format:': ' Audio CD'},Garrett,"This is awesome to listen to, A must-have for ...",Slayer Rules!,1370217600,NaN,0,0
1,5,NaN,True,"10 11, 2014",A3OFSREZADFUDY,3426958910,{'Format:': ' Audio CD'},Ad,bien,Five Stars,1412985600,NaN,1,0
2,5,NaN,True,"02 11, 2014",A2VAMODP8M77NG,3426958910,{'Format:': ' Audio CD'},JTGabq,It was great to hear the old stuff again and I...,SLAYER!!!!!!!!!!!!!!!!!!!!!,1392076800,NaN,2,0
3,4,3.0,False,"12 7, 2013",AAKSLZ9IDTEH0,3426958910,{'Format:': ' Audio CD'},john F&#039;n doe,well best of's are a bit poison normally but t...,slayer greatest hits! you mean everything righ...,1386374400,NaN,3,0
4,5,NaN,True,"06 12, 2016",A3OH43OZJLKI09,5557706259,{'Format:': ' Audio CD'},melinda a goodman,What can I say? This is Casting Crowns!!!This ...,"This is a good, blessing filled",1465689600,NaN,4,1

In [12]:
df['style'].astype(str).unique()

array(["{'Format:': ' Audio CD'}", "{'Format:': ' MP3 Music'}",
       "{'Format:': ' Vinyl'}", 'nan', "{'Format:': ' DVD'}",
       "{'Format:': ' Audio Cassette'}", "{'Format:': ' Vinyl Bound'}",
       "{'Format:': ' Blu-ray'}", "{'Format:': ' Amazon Video'}",
       "{'Format:': ' Blu-ray Audio'}", "{'Format:': ' DVD Audio'}"],
      dtype=object)

In [13]:
df['style'] = df['style'].astype(str)

In [14]:
df['style'] = df['style'].apply(lambda x: x.split(':')[-1].strip(" }'"))

In [15]:
df.head()

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,image,reviewer_idx,unique_prod_idx
0,5,3.0,True,"06 3, 2013",A2TYZ821XXK2YZ,3426958910,Audio CD,Garrett,"This is awesome to listen to, A must-have for ...",Slayer Rules!,1370217600,NaN,0,0
1,5,NaN,True,"10 11, 2014",A3OFSREZADFUDY,3426958910,Audio CD,Ad,bien,Five Stars,1412985600,NaN,1,0
2,5,NaN,True,"02 11, 2014",A2VAMODP8M77NG,3426958910,Audio CD,JTGabq,It was great to hear the old stuff again and I...,SLAYER!!!!!!!!!!!!!!!!!!!!!,1392076800,NaN,2,0
3,4,3.0,False,"12 7, 2013",AAKSLZ9IDTEH0,3426958910,Audio CD,john F&#039;n doe,well best of's are a bit poison normally but t...,slayer greatest hits! you mean everything righ...,1386374400,NaN,3,0
4,5,NaN,True,"06 12, 2016",A3OH43OZJLKI09,5557706259,Audio CD,melinda a goodman,What can I say? This is Casting Crowns!!!This ...,"This is a good, blessing filled",1465689600,NaN,4,1

In [16]:
df.isnull().sum()

overall                 0
vote               162170
verified                0
reviewTime              0
reviewerID              0
asin                    0
style                   0
reviewerName            5
reviewText            158
summary                36
unixReviewTime          0
image              169599
reviewer_idx            0
unique_prod_idx         0
dtype: int64

## User Information

In [27]:
user = df[['reviewerID', 'asin', 'overall', 'reviewText']]

In [28]:
user.head()

,reviewerID,asin,overall,reviewText
0,A2TYZ821XXK2YZ,3426958910,5,"This is awesome to listen to, A must-have for ..."
1,A3OFSREZADFUDY,3426958910,5,bien
2,A2VAMODP8M77NG,3426958910,5,It was great to hear the old stuff again and I...
3,AAKSLZ9IDTEH0,3426958910,4,well best of's are a bit poison normally but t...
4,A3OH43OZJLKI09,5557706259,5,What can I say? This is Casting Crowns!!!This ...

In [34]:
user_pv = pd.pivot_table(user, values='overall', columns=['asin'], index=['reviewerID'])

In [37]:
user_pv.reset_index()

asin,reviewerID,3426958910,5557505946,5557706259,5559166928,7799420340,9434682614,9714721180,9721717150,B000002TTH,...,B01HF1Z8JO,B01HFCKRA8,B01HGB5USC,B01HGB68GK,B01HGOZSHM,B01HHQSCDQ,B01HIY8QVU,B01HJ91HEC,B01HJ91LIY,B01HJ91MTW
0,A0072041HVZ3465DXUOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A0081575F2F9XQSSIYA3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A0638585LHS5R1XDIOGY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A1006TXWG76H0N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A100UXMXYOQU1X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16561,AZXWUZ9PPSOTL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16562,AZY0M1ANDSEPL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16563,AZYOVGJLQ03ML,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16564,AZYPOLLSDVG4K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16565,AZZHILYMITLGM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
user['reviewText'][0]

'This is awesome to listen to, A must-have for all Slayer fans..sadly needed to be a triple disc set..They have so many hits!!'

In [66]:
user['reviewText'].fillna('', inplace=True)

/var/folders/qz/n2_fh26j4sq9p69l7t8bkvnw0000gn/T/ipykernel_8705/2267632824.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user['reviewText'].fillna('', inplace=True)

In [67]:
user['reviewText'].isnull().sum()

0

In [68]:
user['polarity_score'] = user['reviewText'].apply(lambda x: TextBlob(x).sentiment.polarity)

/var/folders/qz/n2_fh26j4sq9p69l7t8bkvnw0000gn/T/ipykernel_8705/2812514275.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user['polarity_score'] = user['reviewText'].apply(lambda x: TextBlob(x).sentiment.polarity)

In [69]:
user.head()

,reviewerID,asin,overall,reviewText,polarity_score
0,A2TYZ821XXK2YZ,3426958910,5,"This is awesome to listen to, A must-have for ...",0.890625
1,A3OFSREZADFUDY,3426958910,5,bien,0.000000
2,A2VAMODP8M77NG,3426958910,5,It was great to hear the old stuff again and I...,0.345455
3,AAKSLZ9IDTEH0,3426958910,4,well best of's are a bit poison normally but t...,0.328053
4,A3OH43OZJLKI09,5557706259,5,What can I say? This is Casting Crowns!!!This ...,0.550000

In [17]:
df.shape

(169781, 14)

In [18]:
n_users = df['reviewerID'].unique().shape[0]
n_products = df['asin'].unique().shape[0]

In [19]:
n_users, n_products

(16566, 11797)

In [20]:
for i in df.itertuples():
    print(i)
    print(i[0])
    break

Pandas(Index=0, overall=5, vote=3.0, verified=True, reviewTime='06 3, 2013', reviewerID='A2TYZ821XXK2YZ', asin='3426958910', style='Audio CD', reviewerName='Garrett', reviewText='This is awesome to listen to, A must-have for all Slayer fans..sadly needed to be a triple disc set..They have so many hits!!', summary='Slayer Rules!', unixReviewTime=1370217600, image=nan, reviewer_idx=0, unique_prod_idx=0)
0

In [65]:
data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [93]:
data_matrix = np.zeros((n_users, n_products))
for line in df.itertuples():
    data_matrix[line[-1], line[-2]] = line[1]

In [94]:
data_matrix

array([[5., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [96]:
user_similarity = pairwise_distances(data_matrix, metric='cosine')
item_similarity = pairwise_distances(data_matrix.T, metric='cosine')

In [98]:
len(user_similarity[0])

16566

In [99]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
        #We use np.newaxis so that mean_user_rating has same format as ratings
        ratings_diff = (ratings - mean_user_rating[:, np.newaxis])
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])
    return pred

In [100]:
predict(data_matrix, user_similarity, type='user')

array([[ 1.53512952e-03,  3.44230817e-03,  3.62367872e-03, ...,
         2.08393017e-03,  2.17271437e-03,  2.05180068e-03],
       [ 1.25420034e-03,  3.10126712e-03,  3.28251050e-03, ...,
         1.77214900e-03,  1.83256346e-03,  1.71173454e-03],
       [-4.54198203e-04,  1.40561411e-03,  1.58685213e-03, ...,
         4.50917223e-05,  1.36947985e-04,  1.61226397e-05],
       ...,
       [ 7.58907779e-05,  1.40435011e-03,  1.58550366e-03, ...,
         7.58907779e-05,  1.36275293e-04,  1.55062627e-05],
       [ 7.61766598e-05,  1.40458587e-03,  1.58573258e-03, ...,
         7.61766598e-05,  1.36558897e-04,  1.57944229e-05],
       [ 5.00050638e-04,  1.82849955e-03,  2.00965167e-03, ...,
         5.00050638e-04,  5.60434679e-04,  4.39666596e-04]])

In [8]:
user_freq = df[['reviewerID', 'asin']].groupby(
    'reviewerID').count().reset_index()
user_freq.columns = ['reviewerID', 'asin']
user_freq.head()

             reviewerID  asin
0  A0072041HVZ3465DXUOR    42
1  A0081575F2F9XQSSIYA3    10
2  A0638585LHS5R1XDIOGY     6
3        A1006TXWG76H0N    14
4        A100UXMXYOQU1X     9

In [11]:
mean_rating = df.groupby('asin')[['overall']].mean()
# Lowest rated movies
lowest_rated = mean_rating['overall'].idxmin()
# movies.loc[movies['asin'] == lowest_rated]
# # Highest rated movies
# highest_rated = mean_rating['overall'].idxmax()
# movies.loc[movies['asin'] == highest_rated]
# # show number of people who rated movies rated movie highest
# ratings[ratings['asin']==highest_rated]
# # show number of people who rated movies rated movie lowest
# ratings[ratings['asin']==lowest_rated]
 
# ## the above movies has very low dataset. We will use bayesian average
# movie_stats = ratings.groupby('asin')[['overall']].agg(['count', 'mean'])
# movie_stats.columns = movie_stats.columns.droplevel()

In [12]:
mean_rating

             overall
asin
3426958910  4.800000
5557505946  5.000000
5557706259  4.600000
5559166928  4.900000
7799420340  4.784615
...              ...
B01HHQSCDQ  4.857143
B01HIY8QVU  4.823529
B01HJ91HEC  4.928571
B01HJ91LIY  4.800000
B01HJ91MTW  5.000000

[11797 rows x 1 columns]